apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: azure-arc-sample
  namespace: arc-k8s-demo
spec:
  releaseName: arc-k8s-demo
  chart:
    git: https://github.com/Azure/iotedge.git
    ref: release/1.1
    path: kubernetes/charts/
  values:
    serviceName: arc-k8s-demo