apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: iot-edge
  namespace: iotedge
spec:
  releaseName: iot-edge
  chart:
    git: https://github.com/Azure/iotedge.git
    ref: release/1.1
    path: kubernetes/charts/edge-kubernetes
  values:
    serviceName: arc-k8s-demo